# my_mass=int(input("what is your mass? "))
# my_height=float(input("what is your height in meters? "))

# my_bmi=str(my_mass/(my_height**2))
# # print("MY BODY MASS INDEX IS: " + my_bmi)
# name=input("enter your name: ")
# my_height=input("please enter you height: ")
# my_mass=input("please enter your mass: ")
# Mywinning= True
# print(f"hello {name} it is nice to meet you. Your height is {my_height} and your mass is {my_mass}. Also, you winning is very {Mywinning}")
age=int(input("hello, please input your age: "))
days_left=str(90*365-age*365)
weeks_left=str(90*52-age*52)
years_left=str(90-age)
months_left=str(90*12-age*12)
print("you have " + days_left + " days left")
print("you have " + weeks_left + " weeks left")
print("you have " + years_left + " years left")
print("you have " + months_left + " months left")